init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off
artifacts:
  - path: build\*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: DNlnRj4Pz5OWJJhdyDt4KXOCY/jJubNywiNvL22JgwcfkVL4LJ1pmtCXQLTQDSHi
